version: '3.7'

volumes:
  db_data:

services:
  car_detect_bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - event-scheduler_default

  web:
    build:
      context: web
      dockerfile: Dockerfile
    command: [ "gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "app:app" ]
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - event-scheduler_default

  nginx:
    build: ./nginx
    ports:
      - "0.0.0.0:8099:80"
    depends_on:
      - web

networks:
  event-scheduler_default:
    external: true
