version: '3.7'

volumes:
  db_data:


services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:14.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_EXTENSIONS: pg_trgm
    env_file:
      - .env
    ports:
      - "5434:5432"
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8088:8080

  web:
    build:
      context: web
      dockerfile: Dockerfile
    command: ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "app:app"]
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "0.0.0.0:8099:80"
    depends_on:
      - web