version: '3.7'

services:
  spy_cat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spy_cat
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - event-scheduler_default

networks:
  event-scheduler_default:
    external: true
